name: Node CI

on:
  push:
    branches:
    - eWallet
    - '!develop'
    - '!releases/*'
    - '!hotfix/*'
    - '!feature/*'

jobs:
  build:

    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [10.4]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: |
        yarn --ignore-engines
        yarn package-ci
      env:
        CI: true
        ELECTRON_CACHE: $HOME/.cache/electron
        ELECTRON_BUILDER_CACHE: $HOME/.cache/electron-builder
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
